### ISSUE TITLE
[Bug] 1. Querying with one large polygon vs several smaller polygons; 2. scenes fall outside of query WKT

### ISSUE THREAD

**Issue by timatcambrio** [asfadmin/Discovery-asf_search#108]
**Describe the bug**
Suppose one wishes to either (1) break a large rectangular polygon into smaller rectangular polygons, or (2) consolidate several smaller and contiguous rectangular polygon into one large rectangular polygon. Keeping other query parameters constant, as long as the large rectangular polygon and the union of the smaller rectangular polygons cover the exact same area, one should expect the query to return identical set of scenes. This is not the case.

Moreover, one would expect the scenes returned with a given WKT polygon should fall inside of the given WKT polygon. Some scenes do not.

**To Reproduce**
1. Run the attached `test_asf_polygon.txt` script. (I cannot attach `.py` files so I edited the extension.)

**Expected behavior**
1. The number of scenes returned from using one large polygon vs several smaller polygons covering the same area should be the same; they are not.
2. All returned scene footprints should fall inside of the WKT; some do not.

**Desktop (please complete the following information):**
 - OS: macOS 12.4
 - `asf_search`: 3.2.2
 - Python: 3.9.10

[test_asf_polygon.txt](https://github.com/asfadmin/Discovery-asf_search/files/8881109/test_asf_polygon.txt)

**Comment by glshort** [comment]
For very wide shapes, it is generally recommended to subdivide. CMR, the ultimate backend behind all of our search functionality, interpolates between points using the shortest path, by way of great arcs. Thus, when two points in a shape are very far apart in longitude, the arc that connects them can have a very significant sweep north or south in comparison with a linear interpolation between those points in a mercator projection.

Here is a comparison of interpolating between points in mercator vs. the implied arc used to interpolate by CMR:

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/956996/174396149-e1a41944-b86d-4bfa-a046-b66fddbe8484.png">

**Comment by timatcambrio** [comment]
I see, @glshort. Thank you for the explanation! Do you have any suggestions on what might be considered a "long" longitudinal span?

**Comment by glshort** [comment]
The difference is always going to be there, even for short spans, it's just more noticeable as the shape gets wider, so really, the question is "what's an acceptable difference in your case?" One factor that may influence the threshold is the size of the footprint of the products themselves, as subdividing more finely than that won't really have much of an effect. The other major factor is latitude, as extreme northern/southern AOIs will exhibit this property more. Just picking a convenient and usually effective threshold, 10° seems pretty good in most cases and would probably be a good place to start. If your search areas are very far north or south, you may want to go to 5°.

I do want to mention one coming change that is directly related to this topic: we have a feature coming that will check to see if the AOI is precisely its own Minimum Bounding Rectangle (that is, the AOI is a lat/lon-aligned rectangle) and if it is, it will make use of CMR's bounding_box approach instead of polygon. In that context, CMR doesn't interpolate with great arcs as it does in other approaches, and you'll get results perfectly in line with what you were expecting in this case, without any subdivision shenanigans.

I don't have an ETA on that feature at the moment, but it's on our current sprint, so roughly "very soon." I'll update this issue when it's been released.

**Comment by glshort** [comment]
Update on this: with the v5.0.0 release, `asf_search` now performs a check to determine if an AOI is its own minimum bounding rectangle (that is, a lat/lon-aligned rectangle.) If it is, the search is performed slightly differently with CMR, leading to results that should precisely align with the specified bounding box.

As an example, using an AOI such as `POLYGON((-166 65,-85 65,-85 66,-166 66,-166 65))` with the previous approach would yield the following results:
<img width="639" alt="image" src="https://user-images.githubusercontent.com/956996/179816842-acc7304e-7eb2-49bd-a589-bd6d68d1cab5.png">

The new method detects that that shape is a bounding box AOI and instead produces the following results:
<img width="736" alt="image" src="https://user-images.githubusercontent.com/956996/179817575-1cc7dbbf-a25c-4b3e-8de7-1613239c9fd8.png">

Enjoy! :)
